package ai

import (
	"context"
	"fmt"
	"os"
	"time"

	"github.com/sashabaranov/go-openai"
)

const defaultSystemPrompt = `You are a developer writing a merge request description for your team.

Write like a human. Be direct. Use simple words. Avoid buzzwords, jargon, and those long hyphenated phrases that nobody actually says out loud. No "cutting-edge solutions" or "robust implementations" - just explain what changed and why.

Your goal is clarity, not perfection. Reviewers should understand:
- What changed
- Why it changed
- What to watch out for (breaking changes, risks, things to test)

Keep it professional but real. This should read like something a developer actually wrote, not something generated by AI.

Be concise. Skip the fluff. If something is obvious from the code, don't over-explain it.

IMPORTANT: When you see date placeholders in the template (like [Date], [YYYY-MM-DD], [Release Date], etc.), always use the current date that will be provided to you. Do not make up dates or use placeholder text.`

const defaultMRTemplate = `# Merge Request Description

## Summary
[Provide a brief overview of what this MR accomplishes]

## Changes Made
[List the key changes]

## Type of Change
- [ ] Feature (new functionality)
- [ ] Bug Fix
- [ ] Documentation Update
- [ ] Code Refactor
- [ ] Performance Improvement
- [ ] Other (please specify)

## Testing Done
[Describe the testing approach and results]

## Breaking Changes
[List any breaking changes or note "None"]

## Related Issues
[Link any related tickets or issues]`

// Client wraps the OpenAI client
type Client struct {
	client *openai.Client
}

// NewClient creates a new AI client with custom proxy
func NewClient() (*Client, error) {
	apiKey := os.Getenv("AI_KEY")
	if apiKey == "" {
		return nil, fmt.Errorf("AI_KEY environment variable not set")
	}

	config := openai.DefaultConfig(apiKey)
	config.BaseURL = "https://proxy.fuelix.ai/v1"

	return &Client{
		client: openai.NewClientWithConfig(config),
	}, nil
}

// GenerateMRDescription sends the git context to AI and returns MR description
func (c *Client) GenerateMRDescription(commits, diff, model, systemPrompt, template string) (string, error) {
	// Use provided system prompt or fall back to default
	if systemPrompt == "" {
		systemPrompt = defaultSystemPrompt
	}

	// Use provided template or fall back to default
	if template == "" {
		template = defaultMRTemplate
	}

	prompt := buildPrompt(commits, diff, template)

	resp, err := c.client.CreateChatCompletion(
		context.Background(),
		openai.ChatCompletionRequest{
			Model: model,
			Messages: []openai.ChatCompletionMessage{
				{
					Role:    openai.ChatMessageRoleSystem,
					Content: systemPrompt,
				},
				{
					Role:    openai.ChatMessageRoleUser,
					Content: prompt,
				},
			},
		},
	)
	if err != nil {
		return "", fmt.Errorf("OpenAI API call failed: %v", err)
	}

	if len(resp.Choices) == 0 {
		return "", fmt.Errorf("no response from AI")
	}

	return resp.Choices[0].Message.Content, nil
}

func buildPrompt(commits, diff, template string) string {
	currentDate := time.Now()
	dateFormatted := currentDate.Format("January 2, 2006") // e.g., "February 11, 2026"
	dateISO := currentDate.Format("2006-01-02")            // e.g., "2026-02-11"

	return fmt.Sprintf(`IMPORTANT: Today's date is %s (ISO format: %s). When you see date placeholders like [Date], [YYYY-MM-DD], or [Release Date] in the template below, use this exact date.

Based on the following git commits and code changes, please fill out this template with a clear, concise description.

TEMPLATE:
%s

## Commits:
%s

## Code Changes:
%s

Please provide a well-structured description following the template above. Remember to use today's date (%s) for any date fields.`,
		dateFormatted, dateISO, template, commits, diff, dateFormatted)
}
